In [ ]:
# Comes to append(),insert(),delete() ----- axis=1(column),axis=0(rows)
# numpy.append(ndarrayobj,Value) use the function add a value for 1-D at the end of the list.
# numpy.append(ndarrayobj,[Value1,value2,....] or (Value1,value2,....)) use the function add multiple values for 1-D at the end of the list.

In [6]:
# numpy.insert(ndarrayobj,Value) use the function add a value for 1-D at the end of the list.
import numpy as np
a=np.array([10,20,50,70,100])
print("Before appending the value")
print(a,type(a))

Before appending the value
[ 10  20  50  70 100] <class 'numpy.ndarray'>


In [7]:
print("after appending the value")
a=np.append(a,101)
print(a,type(a))

after appending the value
[ 10  20  50  70 100 101] <class 'numpy.ndarray'>


In [8]:
print("after appending the value")
print(np.append(a,105))

after appending the value
[ 10  20  50  70 100 101 105]


In [10]:
# numpy.insert(ndarrayobj,[Value1,value2,....]) use the function add a values at the end of the list.
import numpy as np
a=np.array([10,20,50,70,100])
print("Before appending the value")
print(a,type(a))
a=np.append(a,[110,120,130])
print("after appending the value")
print(a,type(a))

Before appending the value
[ 10  20  50  70 100] <class 'numpy.ndarray'>
after appending the value
[ 10  20  50  70 100 110 120 130] <class 'numpy.ndarray'>


In [12]:
# numpy.insert(ndarrayobj,[Value1,value2,....] or (Value1,value2,....)) use the function add a values at the end of the list.
import numpy as np
a=np.array([10,20,50,70,100])
print("Before appending the value")
print(a,type(a))
a=np.append(a,(110,120,130))
print("after appending the value")
print(a,type(a))

Before appending the value
[ 10  20  50  70 100] <class 'numpy.ndarray'>
after appending the value
[ 10  20  50  70 100 110 120 130] <class 'numpy.ndarray'>


In [13]:
# numpy.insert(ndarrayobj,Value,axis=0 or 1) use the function add a value for 2-D at the end of the list.
import numpy as np
a=np.array([10,20,50,70,100,110]).reshape(2,3)
print("Before appending the value")
print(a,type(a))

Before appending the value
[[ 10  20  50]
 [ 70 100 110]] <class 'numpy.ndarray'>


In [24]:
a=np.append(a,[[11],[22]],axis=1) # Column Wise appending
print(a)

[[ 10  20  50  11]
 [ 70 100 110  22]]


In [25]:
a=np.append(a,[[55],[5]],axis=1) # Column Wise appending
print(a)

[[ 10  20  50  11  55]
 [ 70 100 110  22   5]]


In [28]:
a=np.append(a,[[55,5,15,25,16]],axis=0) # row Wise appending
print(a)

[[ 10  20  50  11  55]
 [ 70 100 110  22   5]
 [ 55   5  15  25  16]]


In [29]:
a=np.append(a,[[1,2,3,4,5]],axis=0) # row Wise appending
print(a)

[[ 10  20  50  11  55]
 [ 70 100 110  22   5]
 [ 55   5  15  25  16]
 [  1   2   3   4   5]]


In [ ]:
#Comes to append(),insert(),delete() ----- axis=1(column),axis=0(rows)
# numpy.insert(ndarrayobj,index,value) use the function add a value for 1-D at the end of the list.
# numpy.insert(ndarrayobj,index,[Value1,value2,....] or (Value1,value2,....)) use the function add multiple values for 1-D at the end of the list.

In [30]:
# numpy.insert(ndarrayobj,index,Value) use the function add a value at particular index for 1-D array list.
import numpy as np
a=np.array([10,20,50,70,100])
print("Before inserting the value")
print(a,type(a))

Before inserting the value
[ 10  20  50  70 100] <class 'numpy.ndarray'>


In [31]:
print("after inserting the value")
a=np.insert(a,0,5)  #at 0th index we insert value 5
print(a,type(a))

after inserting the value
[  5  10  20  50  70 100] <class 'numpy.ndarray'>


In [32]:
print("after inserting the value")
a=np.insert(a,-1,99)  #at 0th index we insert value 5
print(a,type(a))

after inserting the value
[  5  10  20  50  70  99 100] <class 'numpy.ndarray'>


In [39]:
print("after inserting the value")
a=np.insert(a,3,(30,40))  #at 0th index we insert value 5
print(a,type(a))

after inserting the value
[  1   2   3  30  40   1   2   3   5  10  20  30  40  50  70  99 100] <class 'numpy.ndarray'>


In [42]:
# numpy.insert(ndarrayobj,index,Value,axis=0 or 1) use the function add a value at particular index for 2-D array list.
import numpy as np
a=np.array([10,20,50,70,100,22])
print("Before appending the value")
a.shape=(3,2)
print(a)

Before appending the value
[[ 10  20]
 [ 50  70]
 [100  22]]


In [80]:
a=np.insert(a,[2,5],[30,90])
print(a)

[ 10  20  30  50  70 100  90 110  30  55]


In [43]:
print("after inserting the value to the 2D array Row wise")
a=np.insert(a,0,[[1,2]],axis=0)
print(a)

after inserting the value t 2D array
[[  1   2]
 [ 10  20]
 [ 50  70]
 [100  22]]


In [51]:
print("after inserting the value to the 2D array column wise")
a=np.array([1,2,3,4,5,6]).reshape(3,2)
a=np.insert(a,1,[[10,11]],axis=0)
print(a)

after inserting the value to the 2D array column wise
[[ 1  2]
 [10 11]
 [ 3  4]
 [ 5  6]]


In [53]:
a=np.insert(a,-1,[[99,100]],axis=0)
print(a)

[[  1   2]
 [ 99 100]
 [ 10  11]
 [  3   4]
 [ 99 100]
 [  5   6]]


In [54]:
print(a)

[[  1   2]
 [ 99 100]
 [ 10  11]
 [  3   4]
 [ 99 100]
 [  5   6]]


In [61]:
a=np.array([1,2,3,4,5,6]).reshape(3,2)
a=np.insert(a,1,[[99,88,77]],axis=1)
print(a)

[[ 1 99  2]
 [ 3 88  4]
 [ 5 77  6]]


In [62]:
a=np.insert(a,-1,[[50,60,70]],axis=1)
print(a)

[[ 1 99 50  2]
 [ 3 88 60  4]
 [ 5 77 70  6]]


In [63]:
a=np.insert(a,2,[[15,25,35,45]],axis=0)
print(a)

[[ 1 99 50  2]
 [ 3 88 60  4]
 [15 25 35 45]
 [ 5 77 70  6]]


In [65]:
a=np.insert(a,2,[[9,8,7,6]],axis=0)
print(a)

[[ 1 99 50  2]
 [ 3 88 60  4]
 [ 9  8  7  6]
 [15 25 35 45]
 [ 5 77 70  6]]


In [ ]:
# Comes to append(),insert(),delete() ----- axis=1(column),axis=0(rows)
# numpy.delete(ndarrayobj,indexvalue) use the function delete a value based on index for 1-D at the end of the list.

In [66]:
import numpy as np
a=np.array([10,20,50,70,100,110])
print("Before appending the value")
print(a,type(a))

Before appending the value
[ 10  20  50  70 100 110] <class 'numpy.ndarray'>


In [69]:
a=np.delete(a,0)
print(a)

[ 20  50  70 100 110]


In [70]:
a=np.delete(a,3)
print(a)

[ 20  50  70 110]


In [71]:
a=np.delete(a,-2)
print(a)

[ 20  50 110]


In [75]:
import numpy as np
a=np.array([10,20,50,70,100,110,30,55,99,0,45,12]).reshape(3,4)
print("Before appending the value")
print(a,type(a))

Before appending the value
[[ 10  20  50  70]
 [100 110  30  55]
 [ 99   0  45  12]] <class 'numpy.ndarray'>


In [77]:
a=np.delete(a,2,axis=0)
print(a)

[[ 10  20  50  70]
 [100 110  30  55]]


In [79]:
print(np.delete(a,1,axis=1))

[[ 10  50  70]
 [100  30  55]]
